---
services:
  cxp:
    image: devopsteen/cxp:latest  # use alpine tag for a lighter image
    container_name: container-exporter
    volumes: [/var/run/docker.sock:/var/run/docker.sock]
    ports: [8000:8000]
    environment:
      CONTAINER_EXPORTER_PORT: ${CONTAINER_EXPORTER_PORT}
    restart: always

  storm-supervisor:
    image: storm
    restart: always
    command: [storm, supervisor]
    network_mode: host
    volumes:
      - ./config/hosts.cloud:/etc/hosts:ro
      - ./config/storm.cloud.yml:/conf/storm.yaml
    deploy:
      resources:
        limits:
          memory: 600M
          cpus: 1
