---
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports: [2181:2181]
    deploy:
      resources:
        limits:
          memory: 512m

  nimbus:
    image: storm
    container_name: nimbus
    restart: always
    command: [storm, nimbus]
    volumes:
      - ./config/hosts.cloud:/etc/hosts:ro
      - ./config/storm.yml:/conf/storm.yaml
      - ./stormsmarthome/target/:/topologies/:ro
    depends_on: [zookeeper]
    links: [zookeeper]
    ports: [6627:6627]
    environment: [STORM_NIMBUS_JAVA_OPTS="-Xms1g -Xmx2g"]
    deploy:
      resources:
        limits:
          memory: 2G

  storm-ui:
    image: storm
    restart: always
    command: [storm, ui]
    volumes:
      - ./config/hosts.cloud:/etc/hosts:ro
      - ./config/storm.yml:/conf/storm.yaml
    ports: [8081:8081]
    depends_on: [zookeeper, nimbus]
    links: [zookeeper, nimbus]

  mysql:
    image: mysql:8.4.2
    command: --mysql-native-password=ON
    container_name: mysql
    networks:
      storm_network:
    environment:
      MYSQL_ROOT_PASSWORD: Uet123
      MYSQL_DATABASE: iotdata
      MYSQL_USER: user1
      MYSQL_PASSWORD: Uet123
    ports: [3306:3306]
    volumes: [mysql_data:/var/lib/mysql]

volumes:
  mysql_data:

include:
  - path: ./storm-exporter/docker-compose.cloud.yml
