---
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports: [2181:2181]

  nimbus:
    image: storm
    container_name: nimbus
    restart: always
    command: [storm, nimbus]
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./config/storm.yml:/conf/storm.yaml
      - ./stormsmarthome/target/:/topologies/:ro
    depends_on: [zookeeper]
    links: [zookeeper]
    ports: [6627:6627]

  storm-ui:
    image: storm
    restart: always
    command: [storm, ui]
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./config/storm.yml:/conf/storm.yaml
    ports: [8081:8081]
    depends_on: [zookeeper, nimbus]
    links: [zookeeper, nimbus]

  storm-supervisor:
    image: storm
    restart: always
    command: [storm, supervisor]
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./config/storm.yml:/conf/storm.yaml
    deploy:
      replicas: 4
      resources:
        limits:
          memory: 1G
          cpus: 1
