---
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports: [2181:2181]
    deploy:
      resources:
        limits:
          memory: 512m

  nimbus:
    image: storm
    container_name: nimbus
    restart: always
    command: [storm, nimbus]
    volumes:
      - ./config/storm.yml:/conf/storm.yaml
      - ./stormsmarthome/target/:/topologies/:ro
    depends_on: [zookeeper]
    links: [zookeeper]
    ports: [6627:6627]
    environment: [STORM_NIMBUS_JAVA_OPTS="-Xms1g -Xmx2g"]
    deploy:
      resources:
        limits:
          memory: 2G

  storm-ui:
    image: storm
    restart: always
    command: [storm, ui]
    volumes:
      - ./config/storm.yml:/conf/storm.yaml
    ports: [8081:8081]
    depends_on: [zookeeper, nimbus]
    links: [zookeeper, nimbus]

  storm-supervisor:
    image: storm
    restart: always
    command: [storm, supervisor]
    volumes:
      - ./config/storm.yml:/conf/storm.yaml
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 600M
          cpus: 1
    depends_on: [nimbus, zookeeper]

  mysql:
    image: mariadb
    container_name: mysql
    environment:
      MARIADB_ROOT_PASSWORD: Uet123
      MARIADB_DATABASE: iotdata
      MARIADB_USER: user1
      MARIADB_PASSWORD: Uet123
    ports: [3306:3306]
    volumes: [mysql_data:/var/lib/mysql]

volumes:
  mysql_data:

include:
  - path: ./storm-exporter/docker-compose.yml
