---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storm-config
data:
  storm.yaml: |-
    storm.zookeeper.servers:
      - "zookeeper"
    storm.zookeeper.port: 2181
    nimbus.seeds:
      - "storm-nimbus"
    supervisor.slots.ports: [6700]

    topology.spread.components:
      - split-1
      - split-5
      - split-10
      - split-15
      - split-20
      - split-30
      - split-60
      - split-120

    topology.worker.childopts: "-Xmx1024m"
