---
services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    environment:
      - CONTAINERS=1  # optional
      - EVENTS=1  # optional
      - PING=1  # optional
      - VERSION=1  # optional
    volumes: [/var/run/docker.sock:/var/run/docker.sock:ro]
    restart: unless-stopped
    read_only: true
    tmpfs: [/run]

  storm-exporter:
    build:
      context: .
    container_name: storm-exporter
    restart: always
    environment:
      - STORM_UI_HOST=${STORM_UI_HOST}:${STORM_UI_PORT}  # default localhost:8081
      - REFRESH_INTERVAL=${STORM_EXPORTER_REFRESH_INTERVAL}  # default 5
      - EXPORTER_LISTEN_ADDR=:${STORM_EXPORTER_PORT}
      - DOCKER_HOST=tcp://socket-proxy:2375
    ports: ['${STORM_EXPORTER_PORT}:${STORM_EXPORTER_PORT}']
    depends_on: [socket-proxy]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes: [./configs/prometheus.yml:/etc/prometheus/prometheus.yml]
    ports: [9090:9090]

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports: [3000:3000]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default login: admin/admin
    volumes: [grafana-data:/var/lib/grafana]

volumes:
  grafana-data:
