---
storm.zookeeper.servers: [10.148.0.20]
nimbus.seeds: [nimbus.thesis-storm_default]
ui.port: 8081

supervisor.slots.ports:
  - 6700  # Define a single port for the 1 CPU slot

supervisor.memory.capacity.mb: 600
supervisor.cpu.capacity: 100
