---
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  - job_name: storm_exporter
    static_configs:
      - targets: [storm-exporter:8082]

  - job_name: container_exporter
    static_configs:
      - targets:
          - 10.148.0.3:8000
          - 10.148.0.4:8000
          - 10.148.0.5:8000
          - 10.148.0.6:8000
          - 10.148.0.7:8000
rule_files: [recording_rules.yml]
